### ISSUE TITLE
`config.yml` must be adapted to the new format

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-puppet#475]
Based on https://github.com/wazuh/wazuh-packages/issues/1413 we need to modify the current repository use of `config.yml` file.

**Comment by c-bordon** [comment]
@alberpilot  At this time it is not necessary to make this change since with puppet we perform an All in One deployment, so the config.yml file does not need these changes:

```
[root@centos72 ~]# cat /tmp/config.yml 
nodes:
  indexer:
    - name: indexer
      ip: 127.0.0.1
  server:
    - name: server
      ip: 127.0.0.1
  dashboard:
    - name: dashboard
      ip: 127.0.0.1
```
```
[root@centos72 tmp]# ls -la wazuh-certificates/
total 20
dr-x------.  2 root root   82 Apr  7 18:02 .
drwxrwxrwt. 12 root root 4096 Apr  7 18:02 ..
-r--------.  1 root root 1704 Apr  7 18:02 admin-key.pem
-r--------.  1 root root 1107 Apr  7 18:02 admin.pem
-r--------.  1 root root 1704 Apr  7 18:02 root-ca.key
-r--------.  1 root root 1184 Apr  7 18:02 root-ca.pem
```

Without the change:
```
[root@centos72 tmp]# cat config.yml 
nodes:
  indexer:
    name: indexer
    ip: 127.0.0.1
  server:
    name: server
    ip: 127.0.0.1
  dashboard:
    name: dashboard
    ip: 127.0.0.1

```

```
[root@centos72 tmp]# ls -la wazuh-certificates/
total 44
dr-x------.  2 root root  210 Apr  7 18:02 .
drwxrwxrwt. 12 root root 4096 Apr  7 18:02 ..
-r--------.  1 root root 1704 Apr  7 18:02 admin-key.pem
-r--------.  1 root root 1107 Apr  7 18:02 admin.pem
-r--------.  1 root root 1704 Apr  7 18:02 dashboard-key.pem
-r--------.  1 root root 1224 Apr  7 18:02 dashboard.pem
-r--------.  1 root root 1704 Apr  7 18:02 indexer-key.pem
-r--------.  1 root root 1220 Apr  7 18:02 indexer.pem
-r--------.  1 root root 1704 Apr  7 18:02 root-ca.key
-r--------.  1 root root 1184 Apr  7 18:02 root-ca.pem
-r--------.  1 root root 1704 Apr  7 18:02 server-key.pem
-r--------.  1 root root 1220 Apr  7 18:02 server.pem

```
