### ISSUE TITLE
Update the `api.yaml` configuration file with the new `upload_configuration` section and `limits` option

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh-puppet#520]
| |
| - |
| **Target version** |
| 4.4 |

This issue is part of the epic issue https://github.com/wazuh/wazuh/issues/14140.

In the issue https://github.com/wazuh/wazuh/issues/13572, a new API configuration block was created to wrap all the possible configuration limitations through the API. In addition, some options have changed:

- The `remote_commands` will now be enabled or not using the key `allow` instead of `enabled`.
- In addition to the `remote_commands`, we now have a `limits` section.
- As before, the field `allow` will be a boolean.

This is the current block with its default values: 

```yaml
upload_configuration:
  remote_commands:
    localfile:
      allow: True
      exceptions: []
    wodle_command:
      allow: True
      exceptions: []
  limits:
    eps:
      allow: True
```

We should review this repository, update the remote commands and include the new API configuration parameters in the configuration file:

https://github.com/wazuh/wazuh-puppet/blob/0ad32c2acdd65be2dfdaf442fd7c8e62be3dc5de/templates/wazuh_api_yml.erb#L41-L48

Also, new variables might be added to `manager.pp` and `params_manager.pp`:

https://github.com/wazuh/wazuh-puppet/blob/0ad32c2acdd65be2dfdaf442fd7c8e62be3dc5de/manifests/manager.pp#L286-L324

https://github.com/wazuh/wazuh-puppet/blob/0ad32c2acdd65be2dfdaf442fd7c8e62be3dc5de/manifests/params_manager.pp#L349-L397

Consider adding more changes in case they are needed.
