### ISSUE TITLE
Add option for distributed deploy

### ISSUE THREAD

**Issue by vcerenu** [wazuh/wazuh-puppet#632]
In the documentation of Wazuh Puppet deploy only have an example for deploy an AIO and it is necessary add another example about deployment with distributed servers.

**Comment by vcerenu** [comment]
An analysis was made of the changes that are required on the wazuh-puppet repository in order to deploy a distributed environment:
Modify the use of the template for the config.yml. The config.yml file that is currently used is a fixed template that only contains this data:

``` yaml
# config.yml
nodes:
   indexer:
     -name: indexer
       ip: 127.0.0.1
   server:
     - name: server
       ip: 127.0.0.1
   dashboard:
     - name: dashboard
       ip: 127.0.0.1

```
It is necessary to modify the wazuh::certificates class so that when creating the certificates it creates a config.yml file according to the environment that is going to be deployed.

Modify the movement of the `.pem` and `key.pem` keys of each node. These files are created on the same server where Wazuh indexer is going to be deployed, so when moving these files it only moves them to the corresponding directories. This process is generated with hard coded data, since just as the config.yml file is fixed, so are the names of the keys and that is why it performs a move of the exact files, without taking into account variables and so on.

In itself, the dynamics of the current AIO and the distributed environment are very different, since each current class of each product is almost independent, so at the time of installation they do not require previous steps as if the distributed environment requires and it is extremely necessary that the certificates of each domain are generated in one location and then moved, or at least a unique root-ca is generated. Then each node creates its certificates with this root-ca in common, which is currently not contemplated and is done in a very simple way on a single server.

**Comment by vcerenu** [comment]
A new manifest was created where the wazuh::indexer class is declared, which mainly removes many hardcoded options and allows using variables for indexer deployment with more than one node, such as the list of nodes to install.

A new template of the config,yml file was created, to be able to assign variables with the names and IPs of all the nodes for which a certificate is going to be generated. The previous template was too basic and was hardcoded with the names and IPs that belonged to localhost, the new template contemplates different variables assignable by the deployment manifest:

``` yaml
nodes:
   indexer:
     - name: indexer-<%= @indexer_node1_name %>
       ip: <%= @node1-ip %>
     - name: indexer-<%= @indexer_node2_name %>
       ip: <%= @node2-ip %>
     - name: indexer-<%= @indexer_node3_name %>
       ip: <%= @node2-ip %>
   server:
     -name: manager-master
       ip: <%= @master-ip %>
       node_type: master
     -name: manager-worker
       ip: <%= @worker-ip %>
       node_type: worker
   dashboard:
     - name: dashboard
       ip: <%= @dashboard-ip %>
```

A new opensearch.yml template was created since the previous one had the names of all the node certificates hardcoded, so it is necessary to change these values.

The section where the securityadmin was executed, which only has to be run on the main node of the cluster, was removed from within the indexer manifest, and a new class was created to perform this action later.

We worked on a new deployment script, it is not finished but its objective is to be able to assign the necessary variables for the deployment beforehand, such as the names of the nodes and their IPs:

``` ruby
$node1-ip =
$node2-ip =
$node3-ip =
$master-ip =
$worker-ip =
$dashboard-ip =
$indexer_node1_name = 'node1'
$indexer_node2_name = 'node2'
$indexer_node3_name = 'node3'

class['wazuh::certificates-dist']

node "node1" {
  if $facts['os']['family'] == 'Debian' {
    Class['wazuh::repo'] -> Class['apt::update'] -> Package['wazuh-indexer']
  } else {
    Class['wazuh::repo'] -> Package['wazuh-indexer']
  }
  class { 'wazuh::indexer-dist':
   indexer_node_name => "$indexer_node1_name",
   indexer_network_host => "$node1-ip",
  }
}
node "node2" {
  if $facts['os']['family'] == 'Debian' {
    Class['wazuh::repo'] -> Class['apt::update'] -> Package['wazuh-indexer']
  } else {
    Class['wazuh::repo'] -> Package['wazuh-indexer']
  }
  class { 'wazuh::indexer-dist':
   indexer_node_name => "$indexer_node2_name",
   indexer_network_host => "$node2-ip",
  }
}
node "node3" {
  if $facts['os']['family'] == 'Debian' {
    Class['wazuh::repo'] -> Class['apt::update'] -> Package['wazuh-indexer']
  } else {
    Class['wazuh::repo'] -> Package['wazuh-indexer']
  }
  class { 'wazuh::indexer-dist':
   indexer_node_name => "$indexer_node3_name",
   indexer_network_host => "$node3-ip",
  }
}
```

Tests must be done and verification of running securityadmin at the end of the installation and subsequent transfer of the previously created certificates.
